name: Development CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml package
      - name: Set up Maven OSS Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to Maven OSS        
        run: mvn deploy:deploy-file -DgeneratePom=false -DrepositoryId=ossrh -Durl=https://oss.sonatype.org/content/repositories/snapshots/ -Dfile=dist/lib/dwr-${DWR_VERSION}.jar -DpomFile=pom.xml -Dpackaging=jar -Djavadoc=dist/lib/dwr-${DWR_VERSION}-javadoc.jar -Dsources=dist/lib/dwr-${DWR_VERSION}-sources.jar -Dfiles=dist/lib/dwr-${DWR_VERSION}-jdk14.jar -Dclassifiers=jdk14 -Dtypes=jar,jar
        env:
          MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
